# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui
tblhdrList=['Object Name', 'catidx', 'RA', 'DEC', 'Width', 'Length1', 'Length2', 'Tilt', 'Mag', 'Priority',   \
    'in FOV', 'in Mask', '% XOverlap', '% YOverlap', 'Coll catidx']
catcols  = 12
slitcols = 15
refcols = 12
import os, inspect 
import reddir                           # marks source directory
InstructionsFile = open(os.path.dirname(inspect.getfile(reddir)) + "/Instructions.html",'r')

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 817)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 210, 1101, 551))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setBaseSize(QtCore.QSize(200, 200))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        
        #instructions tab
        self.InstructionsTab = QtGui.QWidget()
        self.InstructionsTab.setObjectName("InstructionsTab")
        self.textEditInstructions = QtGui.QTextEdit(self.InstructionsTab)
        self.textEditInstructions.setGeometry(QtCore.QRect(0, 0, 1091, 531))
        self.textEditInstructions.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.textEditInstructions.setObjectName("textEditInstructions")
        self.tabWidget.addTab(self.InstructionsTab, "")
        
        #info tab        
        self.InfoTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InfoTab.sizePolicy().hasHeightForWidth())
        self.InfoTab.setSizePolicy(sizePolicy)
        self.InfoTab.setObjectName("InfoTab")
        self.layoutWidget = QtGui.QWidget(self.InfoTab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 16, 1041, 420))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelInfo_Mode = QtGui.QLabel(self.layoutWidget)
        self.labelInfo_Mode.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelInfo_Mode.setFont(font)
        self.labelInfo_Mode.setObjectName("labelInfo_Mode")
        self.gridLayout_2.addWidget(self.labelInfo_Mode, 0, 0, 1, 2)
        self.radioButtonInfo_Catalogue = QtGui.QRadioButton(self.layoutWidget)
        self.radioButtonInfo_Catalogue.setEnabled(False)
        self.radioButtonInfo_Catalogue.setChecked(True)
        self.radioButtonInfo_Catalogue.setObjectName("radioButtonInfo_Catalogue")
        self.gridLayout_2.addWidget(self.radioButtonInfo_Catalogue, 1, 0, 1, 2)
        self.radioButtonInfo_Manual = QtGui.QRadioButton(self.layoutWidget)
        self.radioButtonInfo_Manual.setEnabled(False)
        self.radioButtonInfo_Manual.setObjectName("radioButtonInfo_Manual")
        self.gridLayout_2.addWidget(self.radioButtonInfo_Manual, 2, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.checkBoxInfo_CentroidOn = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxInfo_CentroidOn.setEnabled(False)
        self.checkBoxInfo_CentroidOn.setChecked(True)
        self.checkBoxInfo_CentroidOn.setObjectName("checkBoxInfo_CentroidOn")
        self.gridLayout_2.addWidget(self.checkBoxInfo_CentroidOn, 3, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line_2 = QtGui.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelInfo_MaskInfo = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelInfo_MaskInfo.setFont(font)
        self.labelInfo_MaskInfo.setObjectName("labelInfo_MaskInfo")
        self.gridLayout_6.addWidget(self.labelInfo_MaskInfo, 0, 0, 1, 1)
        self.labelInfo_ProposalCode = QtGui.QLabel(self.layoutWidget)
        self.labelInfo_ProposalCode.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.labelInfo_ProposalCode.setObjectName("labelInfo_ProposalCode")
        self.gridLayout_6.addWidget(self.labelInfo_ProposalCode, 1, 0, 1, 1)
        self.labelInfo_Proposer = QtGui.QLabel(self.layoutWidget)
        self.labelInfo_Proposer.setObjectName("labelInfo_Proposer")
        self.gridLayout_6.addWidget(self.labelInfo_Proposer, 2, 0, 1, 1)
        self.lineEditInfo_Proposer = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditInfo_Proposer.setObjectName("lineEditInfo_Proposer")
        self.gridLayout_6.addWidget(self.lineEditInfo_Proposer, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(600, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 2, 2, 1, 1)
        self.labelInfo_Creator = QtGui.QLabel(self.layoutWidget)
        self.labelInfo_Creator.setObjectName("labelInfo_Creator")
        self.gridLayout_6.addWidget(self.labelInfo_Creator, 3, 0, 1, 1)
        self.lineEditInfo_Creator = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditInfo_Creator.setObjectName("lineEditInfo_Creator")
        self.gridLayout_6.addWidget(self.lineEditInfo_Creator, 3, 1, 1, 1)
        self.lineEditInfo_ProposalCode = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditInfo_ProposalCode.setObjectName("lineEditInfo_ProposalCode")
        self.gridLayout_6.addWidget(self.lineEditInfo_ProposalCode, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.line_5 = QtGui.QFrame(self.layoutWidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.verticalLayoutInfo_RSSSetup = QtGui.QVBoxLayout()
        self.verticalLayoutInfo_RSSSetup.setObjectName("verticalLayoutInfo_RSSSetup")
        self.labelInfo_RSSSetup = QtGui.QLabel(self.layoutWidget)
#        self.labelInfo_RSSSetup.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelInfo_RSSSetup.setFont(font)
        self.labelInfo_RSSSetup.setTextFormat(QtCore.Qt.RichText)
        self.labelInfo_RSSSetup.setObjectName("labelInfo_RSSSetup")
        self.verticalLayoutInfo_RSSSetup.addWidget(self.labelInfo_RSSSetup)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBoxInfo_Polarimetry = QtGui.QCheckBox(self.layoutWidget)          # khn add
        self.checkBoxInfo_Polarimetry.setEnabled(True)                              # khn add
        self.checkBoxInfo_Polarimetry.setChecked(False)                             # khn add
        self.checkBoxInfo_Polarimetry.setObjectName("checkBoxInfo_Polarimetry")     # khn add
        self.gridLayout.addWidget(self.checkBoxInfo_Polarimetry, 0, 2, 1, 1)        # khn add
        self.checkBoxInfo_ImPol = QtGui.QCheckBox(self.layoutWidget)                # khn add
        self.checkBoxInfo_ImPol.setEnabled(True)                                    # khn add
        self.checkBoxInfo_ImPol.setChecked(False)                                   # khn add
        self.checkBoxInfo_ImPol.setObjectName("checkBoxInfo_ImPol")                 # khn add
        self.gridLayout.addWidget(self.checkBoxInfo_ImPol, 1, 2, 1, 1)              # khn add        
        self.labelInfo_Filter = QtGui.QLabel(self.layoutWidget)
        self.labelInfo_Filter.setEnabled(True)
        self.labelInfo_Filter.setObjectName("labelInfo_Filter")
        self.gridLayout.addWidget(self.labelInfo_Filter, 0, 0, 1, 1)
        self.comboBoxInfo_Filter = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxInfo_Filter.setEnabled(True)
        self.comboBoxInfo_Filter.setObjectName("comboBoxInfo_Filter")
        self.comboBoxInfo_Filter.addItem("")
        self.comboBoxInfo_Filter.addItem("")
        self.comboBoxInfo_Filter.addItem("")
        self.comboBoxInfo_Filter.addItem("")
        self.comboBoxInfo_Filter.addItem("")
        self.gridLayout.addWidget(self.comboBoxInfo_Filter, 0, 1, 1, 1)
        self.labelInfo_Grating = QtGui.QLabel(self.layoutWidget)
        self.labelInfo_Grating.setEnabled(True)
        self.labelInfo_Grating.setObjectName("labelInfo_Grating")
        self.gridLayout.addWidget(self.labelInfo_Grating, 1, 0, 1, 1)
        self.comboBoxInfo_Grating = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxInfo_Grating.setEnabled(True)
        self.comboBoxInfo_Grating.setObjectName("comboBoxInfo_Grating")
        self.comboBoxInfo_Grating.addItem("")                   # khn add NONE
        self.comboBoxInfo_Grating.addItem("")
        self.comboBoxInfo_Grating.addItem("")
        self.comboBoxInfo_Grating.addItem("")
        self.comboBoxInfo_Grating.addItem("")
        self.comboBoxInfo_Grating.addItem("")
        self.comboBoxInfo_Grating.addItem("")
        self.gridLayout.addWidget(self.comboBoxInfo_Grating, 1, 1, 1, 1)
        self.labelInfo_CamAng = QtGui.QLabel(self.layoutWidget)
        self.labelInfo_CamAng.setEnabled(False)
        self.labelInfo_CamAng.setObjectName("labelInfo_CamAng")
        self.gridLayout.addWidget(self.labelInfo_CamAng, 2, 0, 1, 1)
        self.labelInfo_GrAng = QtGui.QLabel(self.layoutWidget)
        self.labelInfo_GrAng.setEnabled(False)
        self.labelInfo_GrAng.setObjectName("labelInfo_GrAng")
        self.gridLayout.addWidget(self.labelInfo_GrAng, 3, 0, 1, 1)
        self.horizontalSliderInfo_CamAng = QtGui.QSlider(self.layoutWidget)
        self.horizontalSliderInfo_CamAng.setEnabled(False)
        self.horizontalSliderInfo_CamAng.setSingleStep(2)
        self.horizontalSliderInfo_CamAng.setProperty("value", 1)
        self.horizontalSliderInfo_CamAng.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderInfo_CamAng.setObjectName("horizontalSliderInfo_CamAng")
        self.gridLayout.addWidget(self.horizontalSliderInfo_CamAng, 2, 2, 1, 1)
        self.horizontalSliderInfo_GrAng = QtGui.QSlider(self.layoutWidget)
        self.horizontalSliderInfo_GrAng.setEnabled(False)
        self.horizontalSliderInfo_GrAng.setSingleStep(2)
        self.horizontalSliderInfo_GrAng.setProperty("value", 1)
        self.horizontalSliderInfo_GrAng.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderInfo_GrAng.setObjectName("horizontalSliderInfo_GrAng")
        self.gridLayout.addWidget(self.horizontalSliderInfo_GrAng, 3, 2, 1, 1)
        self.lineEditInfo_CamAng = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditInfo_CamAng.setEnabled(False)
        self.lineEditInfo_CamAng.setReadOnly(True)
        self.lineEditInfo_CamAng.setObjectName("lineEditInfo_CamAng")
        self.gridLayout.addWidget(self.lineEditInfo_CamAng, 2, 1, 1, 1)
        self.lineEditInfo_GrAng = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditInfo_GrAng.setEnabled(False)
        self.lineEditInfo_GrAng.setReadOnly(True)
        self.lineEditInfo_GrAng.setObjectName("lineEditInfo_GrAng")
        self.gridLayout.addWidget(self.lineEditInfo_GrAng, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(600, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(300, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 2, 1, 1)
        self.verticalLayoutInfo_RSSSetup.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.verticalLayoutInfo_RSSSetup)
        self.tabWidget.addTab(self.InfoTab, "")
        
        #catalog tabs
        self.CatTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CatTab.sizePolicy().hasHeightForWidth())
        self.CatTab.setSizePolicy(sizePolicy)
        self.CatTab.setObjectName("CatTab")
        self.labelCat_Infotext = QtGui.QLabel(self.CatTab)
        self.labelCat_Infotext.setGeometry(QtCore.QRect(9, 9, 928, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        self.labelCat_Infotext.setFont(font)
        self.labelCat_Infotext.setWordWrap(True)
        self.labelCat_Infotext.setObjectName("labelCat_Infotext")
        self.layoutWidget1 = QtGui.QWidget(self.CatTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 1081, 491))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.toolButtonCat_Load = QtGui.QToolButton(self.layoutWidget1)
        self.toolButtonCat_Load.setEnabled(False)
        self.toolButtonCat_Load.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.toolButtonCat_Load.setObjectName("toolButtonCat_Load")
        self.gridLayout_5.addWidget(self.toolButtonCat_Load, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(128, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 1, 1, 1)
        self.pushButtonCat_AddSlits = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonCat_AddSlits.setObjectName("pushButtonCat_AddSlits")
        self.gridLayout_5.addWidget(self.pushButtonCat_AddSlits, 0, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(518, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 0, 3, 1, 1)
        self.pushButtonCat_Clear = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonCat_Clear.setObjectName("pushButtonCat_Clear")
        self.gridLayout_5.addWidget(self.pushButtonCat_Clear, 0, 4, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_5)
        self.line_16 = QtGui.QFrame(self.layoutWidget1)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_6.addWidget(self.line_16)
        self.tableWidgetCat = QtGui.QTableWidget(self.layoutWidget1)
        self.tableWidgetCat.setLineWidth(2)
        self.tableWidgetCat.setRowCount(0)
        self.tableWidgetCat.setObjectName("tableWidgetCat")
        self.tableWidgetCat.setColumnCount(catcols)
        self.tableWidgetCat.setRowCount(0)
        for col in range(catcols):
            item = QtGui.QTableWidgetItem()
            self.tableWidgetCat.setHorizontalHeaderItem(col, item)
        header = self.tableWidgetCat.horizontalHeader()
        header.setResizeMode(0, QtGui.QHeaderView.Stretch)
        for col in range(1,catcols): 
            header.setResizeMode(col, QtGui.QHeaderView.ResizeToContents)                
        self.verticalLayout_6.addWidget(self.tableWidgetCat)
        self.tabWidget.addTab(self.CatTab, "")

        #slit tab
        self.SlitsTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SlitsTab.sizePolicy().hasHeightForWidth())
        self.SlitsTab.setSizePolicy(sizePolicy)
        self.SlitsTab.setObjectName("SlitsTab")
        self.layoutWidget1 = QtGui.QWidget(self.SlitsTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 200, 40))
        self.layoutWidget1.setObjectName("layoutWidget2")        
        self.pushButtonSlit_SaveSlitFile = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonSlit_SaveSlitFile.setObjectName("pushButtonSlit_SaveSlitFile")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        self.layoutWidget2 = QtGui.QWidget(self.SlitsTab)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 48, 1081, 471))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_10 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelSlit_ImportCat = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelSlit_ImportCat.setFont(font)
        self.labelSlit_ImportCat.setObjectName("labelSlit_ImportCat")
        self.gridLayout_4.addWidget(self.labelSlit_ImportCat, 0, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.layoutWidget2)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 0, 1, 3, 1)
        self.labelSlit_ManEdit = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelSlit_ManEdit.setFont(font)
        self.labelSlit_ManEdit.setObjectName("labelSlit_ManEdit")
        self.gridLayout_4.addWidget(self.labelSlit_ManEdit, 0, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(118, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 3, 1, 1)
        self.line_7 = QtGui.QFrame(self.layoutWidget2)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_4.addWidget(self.line_7, 0, 4, 3, 1)
        self.labelSlit_ManEditImage = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelSlit_ManEditImage.setFont(font)
        self.labelSlit_ManEditImage.setObjectName("labelSlit_ManEditImage")
        self.gridLayout_4.addWidget(self.labelSlit_ManEditImage, 0, 5, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(90, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 0, 6, 1, 1)
        self.line_8 = QtGui.QFrame(self.layoutWidget2)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_4.addWidget(self.line_8, 0, 7, 3, 1)
        self.pushButtonSlit_AddSlitImage = QtGui.QPushButton(self.layoutWidget2)
        self.pushButtonSlit_AddSlitImage.setObjectName("pushButtonSlit_AddSlitImage")
        self.gridLayout_4.addWidget(self.pushButtonSlit_AddSlitImage, 1, 5, 2, 1)
        self.pushButtonSlit_DeleteSlitImage = QtGui.QPushButton(self.layoutWidget2)
        self.pushButtonSlit_DeleteSlitImage.setObjectName("pushButtonSlit_DeleteSlitImage")
        self.gridLayout_4.addWidget(self.pushButtonSlit_DeleteSlitImage, 1, 6, 2, 1)
        self.pushButtonSlit_ClearSlits = QtGui.QPushButton(self.layoutWidget2)
        self.pushButtonSlit_ClearSlits.setObjectName("pushButtonSlit_ClearSlits")
        self.gridLayout_4.addWidget(self.pushButtonSlit_ClearSlits, 1, 8, 2, 1)
        self.pushButtonSlit_AddSlitfromCat = QtGui.QPushButton(self.layoutWidget2)
        self.pushButtonSlit_AddSlitfromCat.setObjectName("pushButtonSlit_AddSlitfromCat")
        self.gridLayout_4.addWidget(self.pushButtonSlit_AddSlitfromCat, 1, 0, 2, 1)
        self.pushButtonSlit_AddSlit = QtGui.QPushButton(self.layoutWidget2)
        self.pushButtonSlit_AddSlit.setObjectName("pushButtonSlit_AddSlit")
        self.gridLayout_4.addWidget(self.pushButtonSlit_AddSlit, 1, 2, 2, 1)
        self.pushButtonSlit_DeleteSlit = QtGui.QPushButton(self.layoutWidget2)
        self.pushButtonSlit_DeleteSlit.setObjectName("pushButtonSlit_DeleteSlit")
        self.gridLayout_4.addWidget(self.pushButtonSlit_DeleteSlit, 1, 3, 2, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tableWidgetSlits = QtGui.QTableWidget(self.layoutWidget2)
        self.tableWidgetSlits.setLineWidth(2)
        self.tableWidgetSlits.setRowCount(0)
        self.tableWidgetSlits.setObjectName("tableWidgetSlits")
        self.tableWidgetSlits.setColumnCount(slitcols)
        self.tableWidgetSlits.setRowCount(0)
        for col in range(slitcols):
            item = QtGui.QTableWidgetItem()
            self.tableWidgetSlits.setHorizontalHeaderItem(col, item)
        header = self.tableWidgetSlits.horizontalHeader()
        header.setResizeMode(0, QtGui.QHeaderView.Stretch)
        for col in range(1,slitcols): 
            header.setResizeMode(col, QtGui.QHeaderView.ResizeToContents)
        self.gridLayout_10.addWidget(self.tableWidgetSlits, 2, 0, 1, 1)
        self.line_14 = QtGui.QFrame(self.layoutWidget2)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_10.addWidget(self.line_14, 1, 0, 1, 1)
        self.tabWidget.addTab(self.SlitsTab, "")

        #ref stars
        self.RefstarsTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RefstarsTab.sizePolicy().hasHeightForWidth())
        self.RefstarsTab.setSizePolicy(sizePolicy)
        self.RefstarsTab.setObjectName("RefstarsTab")
        self.layoutWidget4 = QtGui.QWidget(self.RefstarsTab)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 11, 1081, 511))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_11 = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelRef_ImportCat = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelRef_ImportCat.setFont(font)
        self.labelRef_ImportCat.setObjectName("labelRef_ImportCat")
        self.gridLayout_3.addWidget(self.labelRef_ImportCat, 0, 0, 1, 1)
        self.lineRef_line2 = QtGui.QFrame(self.layoutWidget4)
        self.lineRef_line2.setFrameShape(QtGui.QFrame.VLine)
        self.lineRef_line2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineRef_line2.setObjectName("lineRef_line2")
        self.gridLayout_3.addWidget(self.lineRef_line2, 0, 1, 3, 1)
        self.labelRef_ManEdit = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelRef_ManEdit.setFont(font)
        self.labelRef_ManEdit.setObjectName("labelRef_ManEdit")
        self.gridLayout_3.addWidget(self.labelRef_ManEdit, 0, 2, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(138, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 0, 3, 1, 1)
        self.lineRef_line1 = QtGui.QFrame(self.layoutWidget4)
        self.lineRef_line1.setFrameShape(QtGui.QFrame.VLine)
        self.lineRef_line1.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineRef_line1.setObjectName("lineRef_line1")
        self.gridLayout_3.addWidget(self.lineRef_line1, 0, 4, 3, 1)
        self.labelRef_ManEditImage = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelRef_ManEditImage.setFont(font)
        self.labelRef_ManEditImage.setObjectName("labelRef_ManEditImage")
        self.gridLayout_3.addWidget(self.labelRef_ManEditImage, 0, 5, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(138, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 0, 6, 1, 1)
        self.lineRef_line1_2 = QtGui.QFrame(self.layoutWidget4)
        self.lineRef_line1_2.setFrameShape(QtGui.QFrame.VLine)
        self.lineRef_line1_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineRef_line1_2.setObjectName("lineRef_line1_2")
        self.gridLayout_3.addWidget(self.lineRef_line1_2, 0, 7, 3, 1)
        self.pushButtonRef_ClearRefstars = QtGui.QPushButton(self.layoutWidget4)
        self.pushButtonRef_ClearRefstars.setObjectName("pushButtonRef_ClearRefstars")
        self.gridLayout_3.addWidget(self.pushButtonRef_ClearRefstars, 1, 8, 2, 1)
        self.pushButtonRef_AddRefstarsfromCat = QtGui.QPushButton(self.layoutWidget4)
        self.pushButtonRef_AddRefstarsfromCat.setObjectName("pushButtonRef_AddRefstarsfromCat")
        self.gridLayout_3.addWidget(self.pushButtonRef_AddRefstarsfromCat, 2, 0, 1, 1)
        self.pushButtonRef_AddRefstar = QtGui.QPushButton(self.layoutWidget4)
        self.pushButtonRef_AddRefstar.setObjectName("pushButtonRef_AddRefstar")
        self.gridLayout_3.addWidget(self.pushButtonRef_AddRefstar, 2, 2, 1, 1)
        self.pushButtonRef_DeleteRefstar = QtGui.QPushButton(self.layoutWidget4)
        self.pushButtonRef_DeleteRefstar.setObjectName("pushButtonRef_DeleteRefstar")
        self.gridLayout_3.addWidget(self.pushButtonRef_DeleteRefstar, 2, 3, 1, 1)
        self.pushButtonRef_AddRefstarImage = QtGui.QPushButton(self.layoutWidget4)
        self.pushButtonRef_AddRefstarImage.setObjectName("pushButtonRef_AddRefstarImage")
        self.gridLayout_3.addWidget(self.pushButtonRef_AddRefstarImage, 2, 5, 1, 1)
        self.pushButtonRef_DeleteRefstar_2 = QtGui.QPushButton(self.layoutWidget4)
        self.pushButtonRef_DeleteRefstar_2.setObjectName("pushButtonRef_DeleteRefstar_2")
        self.gridLayout_3.addWidget(self.pushButtonRef_DeleteRefstar_2, 2, 6, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tableWidgetRefstars = QtGui.QTableWidget(self.layoutWidget4)
        self.tableWidgetRefstars.setLineWidth(2)
        self.tableWidgetRefstars.setRowCount(0)
        self.tableWidgetRefstars.setObjectName("tableWidgetRefstars")
        self.tableWidgetRefstars.setColumnCount(refcols)
        self.tableWidgetRefstars.setRowCount(0)
        for col in range(refcols):
            item = QtGui.QTableWidgetItem()
            self.tableWidgetRefstars.setHorizontalHeaderItem(col, item)
        header = self.tableWidgetRefstars.horizontalHeader()
        header.setResizeMode(0, QtGui.QHeaderView.Stretch)
        for col in range(1,refcols): 
            header.setResizeMode(col, QtGui.QHeaderView.ResizeToContents)        
        self.gridLayout_11.addWidget(self.tableWidgetRefstars, 2, 0, 1, 1)
        self.line_15 = QtGui.QFrame(self.layoutWidget4)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_11.addWidget(self.line_15, 1, 0, 1, 1)
        self.tabWidget.addTab(self.RefstarsTab, "")
        
        #optimize tab
        self.OptimizeTab = QtGui.QWidget()
        self.OptimizeTab.setObjectName("OptimizeTab")
                
        self.pushButtonOpt_Optimize = QtGui.QPushButton(self.OptimizeTab)
        self.pushButtonOpt_Optimize.setEnabled(True)  
        self.pushButtonOpt_Optimize.setGeometry(QtCore.QRect(20, 30, 93, 27))
        self.pushButtonOpt_Optimize.setObjectName("pushButtonOpt_Optimize")
        
        self.layoutWidget3 = QtGui.QWidget(self.OptimizeTab)
        self.layoutWidget3.setGeometry(QtCore.QRect(21, 80, 151, 95))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayoutOpt1 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayoutOpt1.setObjectName("gridLayoutOpt1")
        
        self.labelOpt_Spacing = QtGui.QLabel(self.layoutWidget3)
        self.labelOpt_Spacing.setEnabled(True)
        self.labelOpt_Spacing.setObjectName("labelOpt_Spacing")
        self.gridLayoutOpt1.addWidget(self.labelOpt_Spacing, 0, 0, 1, 1)        
        self.labelOpt_ShiftCross = QtGui.QLabel(self.layoutWidget3)
        self.labelOpt_ShiftCross.setEnabled(True)        
        self.labelOpt_ShiftCross.setObjectName("labelOpt_ShiftCross")
        self.gridLayoutOpt1.addWidget(self.labelOpt_ShiftCross, 1, 0, 1, 1)
        self.labelOpt_AllowSpec = QtGui.QLabel(self.layoutWidget3)
        self.labelOpt_AllowSpec.setEnabled(True)        
        self.labelOpt_AllowSpec.setObjectName("labelOpt_AllowSpec")
        self.gridLayoutOpt1.addWidget(self.labelOpt_AllowSpec, 2, 0, 1, 1)
                
        self.tableWidgetOptcollParam = QtGui.QTableWidget(self.OptimizeTab)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(font.pointSize()+1)
        self.tableWidgetOptcollParam.setFont(font)        
        
        self.tableWidgetOptcollParam.setGeometry(QtCore.QRect(127, 82, 72, 95))            
        self.tableWidgetOptcollParam.setLineWidth(1)
        self.tableWidgetOptcollParam.setColumnCount(1)
        self.tableWidgetOptcollParam.setRowCount(3)
        self.tableWidgetOptcollParam.verticalHeader().setVisible(False)
        self.tableWidgetOptcollParam.horizontalHeader().setVisible(False)

        self.pushButtonOpt_Adoptit = QtGui.QPushButton(self.OptimizeTab)
        self.pushButtonOpt_Adoptit.setEnabled(False)  
        self.pushButtonOpt_Adoptit.setGeometry(QtCore.QRect(330, 145, 93, 27))
        self.pushButtonOpt_Adoptit.setObjectName("pushButtonOpt_Adoptit")

        self.radioButtonOpt_Start = QtGui.QRadioButton(self.OptimizeTab)
        self.radioButtonOpt_Start.setEnabled(True)
        self.radioButtonOpt_Start.setChecked(False)
        self.radioButtonOpt_Start.setObjectName("radioButtonOpt_Start")
        self.radioButtonOpt_Start.setGeometry(QtCore.QRect(260, 180, 10, 10))  
        self.radioButtonOpt_Best = QtGui.QRadioButton(self.OptimizeTab)
        self.radioButtonOpt_Best.setEnabled(True)
        self.radioButtonOpt_Best.setChecked(False)        
        self.radioButtonOpt_Best.setObjectName("radioButtonOpt_Best")
        self.radioButtonOpt_Best.setGeometry(QtCore.QRect(365, 180, 10, 10))

        self.layoutWidget8 = QtGui.QWidget(self.OptimizeTab)
        self.layoutWidget8.setGeometry(QtCore.QRect(50, 219, 151, 100))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.gridLayoutOpt2 = QtGui.QGridLayout(self.layoutWidget8)      
        self.gridLayoutOpt2.setObjectName("gridLayoutOpt2")
        self.labelOpt_dPAtext = QtGui.QLabel(self.layoutWidget8)
        self.labelOpt_dPAtext.setEnabled(True)
        self.labelOpt_dPAtext.setObjectName("labelOpt_dPAtext")
        self.gridLayoutOpt2.addWidget(self.labelOpt_dPAtext, 0, 0, 1, 1)
        self.labelOpt_dXtext = QtGui.QLabel(self.layoutWidget8)
        self.labelOpt_dXtext.setEnabled(True)
        self.labelOpt_dXtext.setObjectName("labelOpt_dXtext")
        self.gridLayoutOpt2.addWidget(self.labelOpt_dXtext, 1, 0, 1, 1)
        self.labelOpt_dYtext = QtGui.QLabel(self.layoutWidget8)
        self.labelOpt_dYtext.setEnabled(True)
        self.labelOpt_dYtext.setObjectName("labelOpt_dYtext")
        self.gridLayoutOpt2.addWidget(self.labelOpt_dYtext, 2, 0, 1, 1)                

        self.tableWidgetOptsetup = QtGui.QTableWidget(self.OptimizeTab)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(font.pointSize()+1)                
        self.tableWidgetOptsetup.setFont(font)        
        self.tableWidgetOptsetup.setGeometry(QtCore.QRect(90, 200, 115, 120))            
        self.tableWidgetOptsetup.setLineWidth(1)
        self.tableWidgetOptsetup.setColumnCount(2)
        self.tableWidgetOptsetup.setRowCount(3)
        self.tableWidgetOptsetup.verticalHeader().setVisible(False)
        self.tableWidgetOptsetup.setHorizontalHeaderLabels(["Count","Step"])
        self.tableWidgetOptsetup.horizontalHeader().setResizeMode(0, QtGui.QHeaderView.Stretch)
        self.tableWidgetOptsetup.horizontalHeader().setResizeMode(1, QtGui.QHeaderView.ResizeToContents)                 

        self.layoutWidget9 = QtGui.QWidget(self.OptimizeTab)
        self.layoutWidget9.setGeometry(QtCore.QRect(110, 310, 151, 160))      
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.gridLayoutOpt3 = QtGui.QGridLayout(self.layoutWidget9)      
        self.gridLayoutOpt3.setObjectName("gridLayoutOpt3")        
        self.labelOpt_P1Targstext = QtGui.QLabel(self.layoutWidget9)
        self.labelOpt_P1Targstext.setEnabled(True)
        self.labelOpt_P1Targstext.setObjectName("labelOpt_P1Targstext")
        self.gridLayoutOpt3.addWidget(self.labelOpt_P1Targstext, 0, 0, 1, 1)
        self.labelOpt_TotTargstext = QtGui.QLabel(self.layoutWidget9)
        self.labelOpt_TotTargstext.setEnabled(True)
        self.labelOpt_TotTargstext.setObjectName("labelOpt_TotTargstext")
        self.gridLayoutOpt3.addWidget(self.labelOpt_TotTargstext, 1, 0, 1, 1)        
        self.labelOpt_Refstext = QtGui.QLabel(self.layoutWidget9)
        self.labelOpt_Refstext.setEnabled(True)
        self.labelOpt_Refstext.setObjectName("labelOpt_Refstext")
        self.gridLayoutOpt3.addWidget(self.labelOpt_Refstext, 2, 0, 1, 1)
        self.labelOpt_P1Colltext = QtGui.QLabel(self.layoutWidget9)
        self.labelOpt_P1Colltext.setEnabled(True)
        self.labelOpt_P1Colltext.setObjectName("labelOpt_P1Colltext")
        self.gridLayoutOpt3.addWidget(self.labelOpt_P1Colltext, 3, 0, 1, 1)
        self.labelOpt_P1Shifttext = QtGui.QLabel(self.layoutWidget9)
        self.labelOpt_P1Shifttext.setEnabled(True)
        self.labelOpt_P1Shifttext.setObjectName("labelOpt_P1Shifttext")
        self.gridLayoutOpt3.addWidget(self.labelOpt_P1Shifttext, 4, 0, 1, 1)            
        
        self.tableWidgetOptresult = QtGui.QTableWidget(self.OptimizeTab)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(font.pointSize()+1)              
        self.tableWidgetOptresult.setFont(font)
        self.tableWidgetOptresult.setGeometry(QtCore.QRect(210, 200, 225, 270))            
        self.tableWidgetOptresult.setLineWidth(1)
        self.tableWidgetOptresult.setColumnCount(2)
        self.tableWidgetOptresult.setRowCount(8)
        self.tableWidgetOptresult.setColumnWidth(0,110)
        self.tableWidgetOptresult.setColumnWidth(1,110)        
        self.tableWidgetOptresult.verticalHeader().setVisible(False)
        self.tableWidgetOptresult.setHorizontalHeaderLabels(["Start","Best"])                
        self.tableWidgetOptresult.setObjectName("tableWidgetOptresult")
                
        self.tableWidgetOptNudge = QtGui.QTableWidget(self.OptimizeTab)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(font.pointSize()+1)              
        self.tableWidgetOptNudge.setFont(font)
        self.tableWidgetOptNudge.setGeometry(QtCore.QRect(440, 225, 85, 95))            
        self.tableWidgetOptNudge.setLineWidth(1)
        self.tableWidgetOptNudge.setColumnCount(2)
        self.tableWidgetOptNudge.setRowCount(3)
        self.tableWidgetOptNudge.setColumnWidth(0,40)
        self.tableWidgetOptNudge.setColumnWidth(1,40)        
        self.tableWidgetOptNudge.verticalHeader().setVisible(False)
        self.tableWidgetOptNudge.horizontalHeader().setVisible(False)            
        self.tableWidgetOptNudge.setObjectName("tableWidgetOptNudge")       
                        
        self.tabWidget.addTab(self.OptimizeTab, "")

        # finalize tab
        self.FinalizeTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FinalizeTab.sizePolicy().hasHeightForWidth())
        self.FinalizeTab.setSizePolicy(sizePolicy)
        self.FinalizeTab.setObjectName("FinalizeTab")
        self.textEditFin_ErrorMessages = QtGui.QTextEdit(self.FinalizeTab)
        self.textEditFin_ErrorMessages.setEnabled(True)
        self.textEditFin_ErrorMessages.setGeometry(QtCore.QRect(510, 10, 531, 261))
        self.textEditFin_ErrorMessages.setAutoFillBackground(True)
        self.textEditFin_ErrorMessages.setFrameShadow(QtGui.QFrame.Plain)
        self.textEditFin_ErrorMessages.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEditFin_ErrorMessages.setObjectName("textEditFin_ErrorMessages")
        self.layoutWidget5 = QtGui.QWidget(self.FinalizeTab)
        self.layoutWidget5.setGeometry(QtCore.QRect(9, 11, 492, 253))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_19 = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.labelFin_Slitmask = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelFin_Slitmask.setFont(font)
        self.labelFin_Slitmask.setObjectName("labelFin_Slitmask")
        self.gridLayout_19.addWidget(self.labelFin_Slitmask, 0, 0, 1, 1)
        self.pushButtonFin_Validate = QtGui.QPushButton(self.layoutWidget5)
        self.pushButtonFin_Validate.setObjectName("pushButtonFin_Validate")
        self.gridLayout_19.addWidget(self.pushButtonFin_Validate, 1, 0, 1, 1)
        self.toolButtonFin_WriteRSMT = QtGui.QToolButton(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonFin_WriteRSMT.sizePolicy().hasHeightForWidth())
        self.toolButtonFin_WriteRSMT.setSizePolicy(sizePolicy)
        self.toolButtonFin_WriteRSMT.setObjectName("toolButtonFin_WriteRSMT")
        self.gridLayout_19.addWidget(self.toolButtonFin_WriteRSMT, 2, 0, 1, 1)
        self.labelFin_WriteRSMTinfo = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setItalic(True)
        self.labelFin_WriteRSMTinfo.setFont(font)
        self.labelFin_WriteRSMTinfo.setObjectName("labelFin_WriteRSMTinfo")
        self.gridLayout_19.addWidget(self.labelFin_WriteRSMTinfo, 2, 1, 1, 1)
        self.lineFin_3 = QtGui.QFrame(self.layoutWidget5)
        self.lineFin_3.setFrameShape(QtGui.QFrame.HLine)
        self.lineFin_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineFin_3.setObjectName("lineFin_3")
        self.gridLayout_19.addWidget(self.lineFin_3, 3, 0, 1, 3)
        self.labelFin_FChart_3 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelFin_FChart_3.setFont(font)
        self.labelFin_FChart_3.setObjectName("labelFin_FChart_3")
        self.gridLayout_19.addWidget(self.labelFin_FChart_3, 4, 0, 1, 1)
        self.pushButtonFin_WriteXML = QtGui.QPushButton(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFin_WriteXML.sizePolicy().hasHeightForWidth())
        self.pushButtonFin_WriteXML.setSizePolicy(sizePolicy)
        self.pushButtonFin_WriteXML.setObjectName("pushButtonFin_WriteXML")
        self.gridLayout_19.addWidget(self.pushButtonFin_WriteXML, 5, 0, 1, 1)
        self.lineFin = QtGui.QFrame(self.layoutWidget5)
        self.lineFin.setFrameShape(QtGui.QFrame.HLine)
        self.lineFin.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineFin.setObjectName("lineFin")
        self.gridLayout_19.addWidget(self.lineFin, 6, 0, 1, 3)
        self.labelFin_FChart = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelFin_FChart.setFont(font)
        self.labelFin_FChart.setObjectName("labelFin_FChart")
        self.gridLayout_19.addWidget(self.labelFin_FChart, 7, 0, 1, 1)
        self.pushButtonFin_CreateFChart_Current = QtGui.QPushButton(self.layoutWidget5)
        self.pushButtonFin_CreateFChart_Current.setObjectName("pushButtonFin_CreateFChart_Current")
        self.gridLayout_19.addWidget(self.pushButtonFin_CreateFChart_Current, 8, 0, 1, 2)
        self.pushButtonFin_CreateFChart_DSS = QtGui.QPushButton(self.layoutWidget5)
        self.pushButtonFin_CreateFChart_DSS.setObjectName("pushButtonFin_CreateFChart_DSS")
        self.gridLayout_19.addWidget(self.pushButtonFin_CreateFChart_DSS, 9, 0, 1, 2)
        self.labelFin_CreateFChartinfo = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setItalic(True)
        self.labelFin_CreateFChartinfo.setFont(font)
        self.labelFin_CreateFChartinfo.setObjectName("labelFin_CreateFChartinfo")
        self.gridLayout_19.addWidget(self.labelFin_CreateFChartinfo, 9, 2, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem11, 4, 2, 1, 1)
        self.tabWidget.addTab(self.FinalizeTab, "")
        
        # Main window
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(9, 198, 1051, 16))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(420, 10, 16, 183))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.layoutWidget6 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(510, 20, 511, 175))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayoutMain_MaskCoords = QtGui.QVBoxLayout()
        self.verticalLayoutMain_MaskCoords.setObjectName("verticalLayoutMain_MaskCoords")
        self.labelMain_MaskHeading = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.labelMain_MaskHeading.setFont(font)
        self.labelMain_MaskHeading.setObjectName("labelMain_MaskHeading")
        self.verticalLayoutMain_MaskCoords.addWidget(self.labelMain_MaskHeading)
        self.gridLayoutMain_MaskCoords = QtGui.QGridLayout()
        self.gridLayoutMain_MaskCoords.setObjectName("gridLayoutMain_MaskCoords")
        self.labelMain_CenRA = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_CenRA.setFont(font)
        self.labelMain_CenRA.setObjectName("labelMain_CenRA")
        self.gridLayoutMain_MaskCoords.addWidget(self.labelMain_CenRA, 0, 0, 1, 1)
        self.labelMain_CenDEC = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_CenDEC.setFont(font)
        self.labelMain_CenDEC.setObjectName("labelMain_CenDEC")
        self.gridLayoutMain_MaskCoords.addWidget(self.labelMain_CenDEC, 0, 1, 1, 1)
        self.labelMain_Epoch = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_Epoch.setFont(font)
        self.labelMain_Epoch.setObjectName("labelMain_Epoch")
        self.gridLayoutMain_MaskCoords.addWidget(self.labelMain_Epoch, 0, 2, 1, 1)
        self.labelMain_PA = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_PA.setFont(font)
        self.labelMain_PA.setObjectName("labelMain_PA")
        self.gridLayoutMain_MaskCoords.addWidget(self.labelMain_PA, 0, 3, 1, 1)
        self.lineEditMain_CenRA = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEditMain_CenRA.setObjectName("lineEditMain_CenRA")
        self.gridLayoutMain_MaskCoords.addWidget(self.lineEditMain_CenRA, 1, 0, 1, 1)
        self.lineEditMain_CenDEC = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEditMain_CenDEC.setObjectName("lineEditMain_CenDEC")
        self.gridLayoutMain_MaskCoords.addWidget(self.lineEditMain_CenDEC, 1, 1, 1, 1)
        self.lineEditMain_Equinox = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEditMain_Equinox.setObjectName("lineEditMain_Equinox")
        self.gridLayoutMain_MaskCoords.addWidget(self.lineEditMain_Equinox, 1, 2, 1, 1)
        self.lineEditMain_PA = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEditMain_PA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditMain_PA.setObjectName("lineEditMain_PA")
        self.gridLayoutMain_MaskCoords.addWidget(self.lineEditMain_PA, 1, 3, 1, 1)
        self.verticalLayoutMain_MaskCoords.addLayout(self.gridLayoutMain_MaskCoords)
        self.verticalLayout_2.addLayout(self.verticalLayoutMain_MaskCoords)
        self.line = QtGui.QFrame(self.layoutWidget6)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayoutMain_RSSSetup = QtGui.QVBoxLayout()
        self.verticalLayoutMain_RSSSetup.setObjectName("verticalLayoutMain_RSSSetup")
        self.labelMain_RSSHeading = QtGui.QLabel(self.layoutWidget6)
        self.labelMain_RSSHeading.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.labelMain_RSSHeading.setFont(font)
        self.labelMain_RSSHeading.setObjectName("labelMain_RSSHeading")
        self.verticalLayoutMain_RSSSetup.addWidget(self.labelMain_RSSHeading)
        self.gridLayoutMain_RSSSetup = QtGui.QGridLayout()
        self.gridLayoutMain_RSSSetup.setObjectName("gridLayoutMain_RSSSetup")
        self.labelMain_Filter = QtGui.QLabel(self.layoutWidget6)
        self.labelMain_Filter.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_Filter.setFont(font)
        self.labelMain_Filter.setObjectName("labelMain_Filter")
        self.gridLayoutMain_RSSSetup.addWidget(self.labelMain_Filter, 0, 0, 1, 1)
        self.labelMain_Grating = QtGui.QLabel(self.layoutWidget6)
        self.labelMain_Grating.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_Grating.setFont(font)
        self.labelMain_Grating.setObjectName("labelMain_Grating")
        self.gridLayoutMain_RSSSetup.addWidget(self.labelMain_Grating, 0, 1, 1, 1)
        self.labelMain_CamAng = QtGui.QLabel(self.layoutWidget6)
        self.labelMain_CamAng.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_CamAng.setFont(font)
        self.labelMain_CamAng.setObjectName("labelMain_CamAng")
        self.gridLayoutMain_RSSSetup.addWidget(self.labelMain_CamAng, 0, 2, 1, 1)
        self.labelMain_GrAng = QtGui.QLabel(self.layoutWidget6)
        self.labelMain_GrAng.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_GrAng.setFont(font)
        self.labelMain_GrAng.setObjectName("labelMain_GrAng")
        self.gridLayoutMain_RSSSetup.addWidget(self.labelMain_GrAng, 0, 3, 1, 1)
        self.lineEditMain_Filter = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEditMain_Filter.setEnabled(False)
        self.lineEditMain_Filter.setReadOnly(True)
        self.lineEditMain_Filter.setObjectName("lineEditMain_Filter")
        self.gridLayoutMain_RSSSetup.addWidget(self.lineEditMain_Filter, 1, 0, 1, 1)
        self.lineEditMain_Grating = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEditMain_Grating.setEnabled(False)
        self.lineEditMain_Grating.setText("")
        self.lineEditMain_Grating.setReadOnly(True)
        self.lineEditMain_Grating.setObjectName("lineEditMain_Grating")
        self.gridLayoutMain_RSSSetup.addWidget(self.lineEditMain_Grating, 1, 1, 1, 1)
        self.lineEditMain_CamAng = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEditMain_CamAng.setEnabled(False)
        self.lineEditMain_CamAng.setReadOnly(True)
        self.lineEditMain_CamAng.setObjectName("lineEditMain_CamAng")
        self.gridLayoutMain_RSSSetup.addWidget(self.lineEditMain_CamAng, 1, 2, 1, 1)
        self.lineEditMain_GrAng = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEditMain_GrAng.setEnabled(False)
        self.lineEditMain_GrAng.setReadOnly(True)
        self.lineEditMain_GrAng.setObjectName("lineEditMain_GrAng")
        self.gridLayoutMain_RSSSetup.addWidget(self.lineEditMain_GrAng, 1, 3, 1, 1)
        self.verticalLayoutMain_RSSSetup.addLayout(self.gridLayoutMain_RSSSetup)
        self.verticalLayout_2.addLayout(self.verticalLayoutMain_RSSSetup)
        self.layoutWidget7 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget7.setGeometry(QtCore.QRect(21, 21, 301, 126))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayoutMain_Info = QtGui.QGridLayout()
        self.gridLayoutMain_Info.setObjectName("gridLayoutMain_Info")
        self.labelMain_TargetName = QtGui.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_TargetName.setFont(font)
        self.labelMain_TargetName.setObjectName("labelMain_TargetName")
        self.gridLayoutMain_Info.addWidget(self.labelMain_TargetName, 0, 0, 1, 1)
        self.labelMain_MaskName = QtGui.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_MaskName.setFont(font)
        self.labelMain_MaskName.setObjectName("labelMain_MaskName")
        self.gridLayoutMain_Info.addWidget(self.labelMain_MaskName, 2, 0, 1, 1)
        self.lineEditMain_MaskName = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEditMain_MaskName.setAutoFillBackground(False)
        self.lineEditMain_MaskName.setObjectName("lineEditMain_MaskName")
        self.gridLayoutMain_Info.addWidget(self.lineEditMain_MaskName, 2, 1, 1, 1)
        self.lineEditMain_TargetName = QtGui.QLineEdit(self.layoutWidget7)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEditMain_TargetName.setPalette(palette)
        self.lineEditMain_TargetName.setObjectName("lineEditMain_TargetName")
        self.gridLayoutMain_Info.addWidget(self.lineEditMain_TargetName, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayoutMain_Info)
        self.labelMain_Mode = QtGui.QLabel(self.layoutWidget7)
        self.labelMain_Mode.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_Mode.setFont(font)
        self.labelMain_Mode.setObjectName("labelMain_Mode")
        self.verticalLayout_5.addWidget(self.labelMain_Mode)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem12 = QtGui.QSpacerItem(90, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem12, 0, 1, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.labelMain_Centroiding = QtGui.QLabel(self.layoutWidget7)
        self.labelMain_Centroiding.setEnabled(False)
        self.labelMain_Centroiding.setObjectName("labelMain_Centroiding")
        self.gridLayout_7.addWidget(self.labelMain_Centroiding, 0, 1, 1, 1)
        self.labelMain_CentroidingOnOff = QtGui.QLabel(self.layoutWidget7)
        self.labelMain_CentroidingOnOff.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_CentroidingOnOff.setFont(font)
        self.labelMain_CentroidingOnOff.setObjectName("labelMain_CentroidingOnOff")
        self.gridLayout_7.addWidget(self.labelMain_CentroidingOnOff, 0, 2, 1, 1)
        self.lineEditMain_Mode = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEditMain_Mode.setEnabled(False)
        self.lineEditMain_Mode.setReadOnly(True)
        self.lineEditMain_Mode.setObjectName("lineEditMain_Mode")
        self.gridLayout_7.addWidget(self.lineEditMain_Mode, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLoad_Catalogue = QtGui.QAction(MainWindow)
        self.actionLoad_Catalogue.setObjectName("actionLoad_Catalogue")
        self.actionLoad_Image = QtGui.QAction(MainWindow)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.actionLoad_Xml = QtGui.QAction(MainWindow)
        self.actionLoad_Xml.setObjectName("actionLoad_Xml")        
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOnline_user_manual = QtGui.QAction(MainWindow)
        self.actionOnline_user_manual.setObjectName("actionOnline_user_manual")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionLoad_Image)
        self.menuFile.addAction(self.actionLoad_Catalogue)
        self.menuFile.addAction(self.actionLoad_Xml)        
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionOnline_user_manual)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.labelInfo_Proposer.setBuddy(self.lineEditInfo_Proposer)
        self.labelInfo_Creator.setBuddy(self.lineEditInfo_Creator)
        self.labelInfo_Filter.setBuddy(self.comboBoxInfo_Filter)
        self.labelInfo_Grating.setBuddy(self.comboBoxInfo_Grating)
        self.labelInfo_CamAng.setBuddy(self.horizontalSliderInfo_CamAng)
        self.labelInfo_GrAng.setBuddy(self.horizontalSliderInfo_CamAng)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QObject.connect(self.radioButtonInfo_Catalogue, QtCore.SIGNAL("clicked(bool)"), self.toolButtonCat_Load.setEnabled)
        QtCore.QObject.connect(self.radioButtonInfo_Manual, QtCore.SIGNAL("clicked(bool)"), self.toolButtonCat_Load.setDisabled)
        QtCore.QObject.connect(self.comboBoxInfo_Filter, QtCore.SIGNAL("activated(QString)"), self.lineEditMain_Filter.setText)
        QtCore.QObject.connect(self.comboBoxInfo_Grating, QtCore.SIGNAL("activated(QString)"), self.lineEditMain_Grating.setText)
        QtCore.QObject.connect(self.lineEditInfo_CamAng, QtCore.SIGNAL("textChanged(QString)"), self.lineEditMain_CamAng.setText)
        QtCore.QObject.connect(self.lineEditInfo_GrAng, QtCore.SIGNAL("textChanged(QString)"), self.lineEditInfo_GrAng.setText)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "pySlitMask", None, QtGui.QApplication.UnicodeUTF8))
        InstructionsQstr = QtCore.QString.fromAscii(InstructionsFile.read())
        self.textEditInstructions.setHtml(InstructionsQstr)

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InstructionsTab), QtGui.QApplication.translate("MainWindow", "  I&nstructions  ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_Mode.setText(QtGui.QApplication.translate("MainWindow", "Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonInfo_Catalogue.setText(QtGui.QApplication.translate("MainWindow", "Catalogue", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonInfo_Manual.setText(QtGui.QApplication.translate("MainWindow", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxInfo_CentroidOn.setText(QtGui.QApplication.translate("MainWindow", "Centroiding On", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_MaskInfo.setText(QtGui.QApplication.translate("MainWindow", "Mask Info:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_ProposalCode.setText(QtGui.QApplication.translate("MainWindow", "Proposal Code:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_Proposer.setText(QtGui.QApplication.translate("MainWindow", "PI:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_Creator.setText(QtGui.QApplication.translate("MainWindow", "Creator:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_RSSSetup.setText(QtGui.QApplication.translate("MainWindow", "RSS Setup:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxInfo_Polarimetry.setText(QtGui.QApplication.translate("MainWindow", "Polarimetry", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxInfo_ImPol.setText(QtGui.QApplication.translate("MainWindow", "ImPol", None, QtGui.QApplication.UnicodeUTF8))              # khn add
        self.labelInfo_Filter.setText(QtGui.QApplication.translate("MainWindow", "Filter:", None, QtGui.QApplication.UnicodeUTF8))              # khn add
        self.comboBoxInfo_Filter.setItemText(0, QtGui.QApplication.translate("MainWindow", "PC00000", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Filter.setItemText(1, QtGui.QApplication.translate("MainWindow", "PC03200", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Filter.setItemText(2, QtGui.QApplication.translate("MainWindow", "PC03400", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Filter.setItemText(3, QtGui.QApplication.translate("MainWindow", "PC03850", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Filter.setItemText(4, QtGui.QApplication.translate("MainWindow", "PC04600", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_Grating.setText(QtGui.QApplication.translate("MainWindow", "Grating:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Grating.setItemText(0, QtGui.QApplication.translate("MainWindow", "NONE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Grating.setItemText(1, QtGui.QApplication.translate("MainWindow", "PG0300", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Grating.setItemText(2, QtGui.QApplication.translate("MainWindow", "PG0900", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Grating.setItemText(3, QtGui.QApplication.translate("MainWindow", "PG1300", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Grating.setItemText(4, QtGui.QApplication.translate("MainWindow", "PG1800", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Grating.setItemText(5, QtGui.QApplication.translate("MainWindow", "PG2300", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Grating.setItemText(6, QtGui.QApplication.translate("MainWindow", "PG3000", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_CamAng.setText(QtGui.QApplication.translate("MainWindow", "Camera Angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_GrAng.setText(QtGui.QApplication.translate("MainWindow", "Grating Angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InfoTab), QtGui.QApplication.translate("MainWindow", "       &Info       ", None, QtGui.QApplication.UnicodeUTF8))

        self.labelCat_Infotext.setText(QtGui.QApplication.translate("MainWindow", "Input object catalogue. Only needed if Mode is set to Catalogue", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonCat_Load.setText(QtGui.QApplication.translate("MainWindow", "Load Catalogue", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCat_AddSlits.setText(QtGui.QApplication.translate("MainWindow", "Add Selected Slits", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCat_Clear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        for col in range(catcols):
            self.tableWidgetCat.horizontalHeaderItem(col).setText(QtGui.QApplication.translate("MainWindow", tblhdrList[col], None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CatTab), QtGui.QApplication.translate("MainWindow", "  &Catalogue  ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSlit_SaveSlitFile.setText(QtGui.QApplication.translate("MainWindow", "Save as file", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSlit_ImportCat.setText(QtGui.QApplication.translate("MainWindow", "Import from Catalogue:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSlit_ManEdit.setText(QtGui.QApplication.translate("MainWindow", "Manually edit slits:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSlit_ManEditImage.setText(QtGui.QApplication.translate("MainWindow", "Import from image", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSlit_AddSlitImage.setText(QtGui.QApplication.translate("MainWindow", "Add slit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSlit_DeleteSlitImage.setText(QtGui.QApplication.translate("MainWindow", "Delete slit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSlit_ClearSlits.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSlit_AddSlitfromCat.setText(QtGui.QApplication.translate("MainWindow", "Add slits to all catalogue objects", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSlit_AddSlit.setText(QtGui.QApplication.translate("MainWindow", "Add slit", None, QtGui.QApplication.UnicodeUTF8))
        for col in range(slitcols):
            self.tableWidgetSlits.horizontalHeaderItem(col).setText(QtGui.QApplication.translate("MainWindow", tblhdrList[col], None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SlitsTab), QtGui.QApplication.translate("MainWindow", "       &Slits       ", None, QtGui.QApplication.UnicodeUTF8))

        self.labelRef_ImportCat.setText(QtGui.QApplication.translate("MainWindow", "Import from Catalogue:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRef_ManEdit.setText(QtGui.QApplication.translate("MainWindow", "Manually edit refstars:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRef_ManEditImage.setText(QtGui.QApplication.translate("MainWindow", "Import from image", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRef_ClearRefstars.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRef_AddRefstarsfromCat.setText(QtGui.QApplication.translate("MainWindow", "Add refstars from catalogue", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRef_AddRefstar.setText(QtGui.QApplication.translate("MainWindow", "Add refstar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRef_DeleteRefstar.setText(QtGui.QApplication.translate("MainWindow", "Delete refstar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRef_AddRefstarImage.setText(QtGui.QApplication.translate("MainWindow", "Add refstar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRef_DeleteRefstar_2.setText(QtGui.QApplication.translate("MainWindow", "Delete refstar", None, QtGui.QApplication.UnicodeUTF8))
        for col in range(refcols):
            self.tableWidgetRefstars.horizontalHeaderItem(col).setText(QtGui.QApplication.translate("MainWindow", tblhdrList[col], None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RefstarsTab), QtGui.QApplication.translate("MainWindow", "     &Refstars      ", None, QtGui.QApplication.UnicodeUTF8))

        self.pushButtonOpt_Optimize.setText(QtGui.QApplication.translate("MainWindow", "Optimize", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_Spacing.setText(QtGui.QApplication.translate("MainWindow", "Spacing (arcsec):", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_ShiftCross.setText(QtGui.QApplication.translate("MainWindow", "Max %cross shift:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_AllowSpec.setText(QtGui.QApplication.translate("MainWindow", "Max %spec Loss:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOpt_Adoptit.setText(QtGui.QApplication.translate("MainWindow", "Adopt it", None, QtGui.QApplication.UnicodeUTF8))                
        self.labelOpt_dPAtext.setText(QtGui.QApplication.translate("MainWindow", "dPA", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_dXtext.setText(QtGui.QApplication.translate("MainWindow", "dX", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_dYtext.setText(QtGui.QApplication.translate("MainWindow", "dY", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_P1Targstext.setText(QtGui.QApplication.translate("MainWindow", "P1 Targets", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_TotTargstext.setText(QtGui.QApplication.translate("MainWindow", "Tot Targets", None, QtGui.QApplication.UnicodeUTF8))        
        self.labelOpt_Refstext.setText(QtGui.QApplication.translate("MainWindow", "References", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_P1Colltext.setText(QtGui.QApplication.translate("MainWindow", "P1 Collision Tot", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_P1Shifttext.setText(QtGui.QApplication.translate("MainWindow", "P1 Shift Tot", None, QtGui.QApplication.UnicodeUTF8))       
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OptimizeTab), QtGui.QApplication.translate("MainWindow", "    &Optimize     ", None, QtGui.QApplication.UnicodeUTF8))

        self.labelFin_Slitmask.setText(QtGui.QApplication.translate("MainWindow", "Slitmask:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonFin_Validate.setText(QtGui.QApplication.translate("MainWindow", "Validate", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonFin_WriteRSMT.setText(QtGui.QApplication.translate("MainWindow", "Write .rsmt file", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFin_WriteRSMTinfo.setText(QtGui.QApplication.translate("MainWindow", "file to load into PIPT", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFin_FChart_3.setText(QtGui.QApplication.translate("MainWindow", "XML Source", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonFin_WriteXML.setText(QtGui.QApplication.translate("MainWindow", "Write XML Source", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFin_FChart.setText(QtGui.QApplication.translate("MainWindow", "Finder Chart:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonFin_CreateFChart_Current.setText(QtGui.QApplication.translate("MainWindow", "Create Finder Chart from current image", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonFin_CreateFChart_DSS.setText(QtGui.QApplication.translate("MainWindow", "Create finder chart from DSS image", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFin_CreateFChartinfo.setText(QtGui.QApplication.translate("MainWindow", "recommended for deep science images", None, QtGui.QApplication.UnicodeUTF8))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FinalizeTab), QtGui.QApplication.translate("MainWindow", "     &Finalize      ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_MaskHeading.setText(QtGui.QApplication.translate("MainWindow", "Coordinates of Mask Centre:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_CenRA.setText(QtGui.QApplication.translate("MainWindow", "Centre RA:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_CenDEC.setText(QtGui.QApplication.translate("MainWindow", "Centre DEC:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_Epoch.setText(QtGui.QApplication.translate("MainWindow", "Equinox:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_PA.setText(QtGui.QApplication.translate("MainWindow", "Positional Angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_RSSHeading.setText(QtGui.QApplication.translate("MainWindow", "RSS Setup:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_Filter.setText(QtGui.QApplication.translate("MainWindow", "Filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_Grating.setText(QtGui.QApplication.translate("MainWindow", "Grating:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_CamAng.setText(QtGui.QApplication.translate("MainWindow", "Camera Ang.:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_GrAng.setText(QtGui.QApplication.translate("MainWindow", "Grating Ang.:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_TargetName.setText(QtGui.QApplication.translate("MainWindow", "Target Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_MaskName.setText(QtGui.QApplication.translate("MainWindow", "Mask Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_Mode.setText(QtGui.QApplication.translate("MainWindow", "Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_Centroiding.setText(QtGui.QApplication.translate("MainWindow", "Centroiding:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_CentroidingOnOff.setText(QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Catalogue.setText(QtGui.QApplication.translate("MainWindow", "Load Catalogue", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Image.setText(QtGui.QApplication.translate("MainWindow", "Load Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Xml.setText(QtGui.QApplication.translate("MainWindow", "Load Xml", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOnline_user_manual.setText(QtGui.QApplication.translate("MainWindow", "Online user manual", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

